[project]
name = "anemiaiaback"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "externo455", email = "externo455@compartamos.pe" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
anemiaiaback = "anemiaiaback:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
